// Shared TS types/DTOs not generated by Prisma. PLAN.md §25.1.

export type ApiErrorCode =
  | "VALIDATION_ERROR"
  | "NOT_FOUND"
  | "FORBIDDEN"
  | "RATE_LIMITED"
  | "INTERNAL";

// Consistent error response shape across every endpoint — PLAN.md §30.7.
export interface ApiErrorResponse {
  error: {
    code: ApiErrorCode;
    message: string;
    fields?: Record<string, string>;
  };
}
